### ISSUE TITLE
Broke if you both use AMD and commonjs on the same page

### ISSUE THREAD

**Issue by kevinsimper** [JedWatson/classnames#40] opened 2015-06-08 09:52 UTC
The latest release if you use AMD and commonjs/browserify on the same page.

**Comment by dcousens** [comment] 2015-06-08 11:22
Can't we all jut get along.

@JedWatson can we just export like normal, but then just recommend people to use a wrapper that does it properly for them?
In the end, this is a node package.

IMHO, anyway.

**Comment by JedWatson** [comment] 2015-06-08 12:46
@kevinsimper can you please clarify what you mean by "broke"? and how it _should_ behave in that case?

Looks to me like fixing this might be as simple as putting this condition first:

```
if (typeof module !== 'undefined' && module.exports)
```

**Comment by daviferreira** [comment] 2015-06-09 07:50
I'm also curious about what `broke` means here, this is just a very common wrapper, used everywhere. And I'm also curious about the scenario of having both amd and commonjs on the same page.

Cheers!

**Comment by kevinsimper** [comment] 2015-06-09 14:41
If you are on a webpage where you both have requirejs and use browserify, then the module.exports will never run and therefore the browserify version will not work.

Because both amd and module can be defined on the same page. So the `else if` prohibites the use of both.

I can agree that it is stupid to use both on the same page, but sometimes its something you can not decide.

**Comment by JedWatson** [comment] 2015-06-10 02:05
@kevinsimper can you confirm whether my proposed change would work, or would you expect it to expose _both_ CommonJS and AMD? A PR that you've confirmed meets your requirements would be welcome.

**Comment by dcocchia** [comment] 2015-06-28 18:34
I'm seeing this issue when using react-boostrap, which includes classnames as a dependency. I'm also using browserify and babelify to bundle.

<code>Uncaught Error: Mismatched anonymous define() module: function () {
			return classNames;
		}
</code>

This is fixed by flipping the conditions, as @JedWatson suggests:

<code>
	if (typeof module !== 'undefined' && module.exports) {
		module.exports = classNames;
	} else if (typeof define === 'function' && typeof define.amd === 'object' && define.amd) {
		// AMD. Register as an anonymous module.
		define(function () {
			return classNames;
		});
	} else {
		window.classNames = classNames;
	}
</code>

**Comment by rickychien** [comment] 2015-07-26 12:56
I ran into the same problem after #41 merged. My use case is using requirejs but it also provide module.export at 
https://github.com/JedWatson/classnames/blob/master/index.js#L38

therefore, it doesn't execute second conditional statement for this case.

**Comment by daviferreira** [comment] 2015-07-27 07:20
Sorry, @JedWatson :heart:

**Comment by yordis** [comment] 2015-10-29 02:32
@JedWatson is this fixed and published?

**Comment by nilocoelhojunior** [comment] 2016-01-29 12:57
I download bower classnames today:

[### dedupe.js, start line 88](https://github.com/JedWatson/classnames/blob/master/dedupe.js#L88)

```JS

if (typeof module !== 'undefined' && module.exports) {
		console.log("undefined");
		module.exports = classNames;
	} else if (typeof define === 'function' && typeof define.amd === 'object' && define.amd) {
		// register as 'classnames', consistent with npm package name
		define('classnames', [], function () {
			return classNames;
		});
	} else {
		console.log("window")
		window.classNames = classNames;
	}
```

made the change suggested by @dcocchia  and it worked

```JS
if (typeof module !== 'undefined' && module.exports) {
		console.log("undefined");
		module.exports = classNames;
	} else if (typeof define === 'function' && typeof define.amd === 'object' && define.amd) {
		// register as 'classnames', consistent with npm package name
		define(function () {
			return classNames;
		});
	} else {
		console.log("window")
		window.classNames = classNames;
	}
```

**Comment by dcousens** [comment] 2016-12-08 00:16
I'm assuming this was resolved,  please comment if otherwise.

**Closed** 2016-12-08 00:16 UTC
Labels: bug
