### ISSUE TITLE
Typescript is not working properly 

### ISSUE THREAD

**Issue by Utkarshbhimte** [JedWatson/classnames#247] opened 2021-04-27 06:00 UTC
```
Could not find a declaration file for module 'classnames'. '/Users/utkarsh/Documents/code/noggin-v2/node_modules/classnames/index.js' implicitly has an 'any' type.
```
This is the error I am getting 

When I went to the node_modules, there is no index.d.ts file 
![image](https://user-images.githubusercontent.com/13379773/116132607-5cd63680-a6eb-11eb-8818-9a3ace229353.png)

What is happening here? All other libraries are working fine.

**Comment by dcousens** [comment] 2021-04-27 06:03
Duplicate of https://github.com/JedWatson/classnames/issues/246

**Closed by dcousens** 2021-04-27 06:03 UTC
