### ISSUE TITLE
Allow replacing of previous class names

### ISSUE THREAD

**Issue by longlho** [JedWatson/classnames#18] opened 2015-03-23 18:23 UTC
My use case is something like `classNames('foo', { foo: false, bar: true })` should render out `class="bar"` instead of `class="foo bar"`. Should this be supported by the library or is this out of scope? I'd be glad to submit a PR if this use case is something you guys plan to support.

**Comment by cezar-berea** [comment] 2015-03-24 09:11
:+1:  on this.

**Comment by JedWatson** [comment] 2015-03-27 01:20
As long as there isn't a negative performance impact, I think this is a reasonable change to the API.

**Comment by dcousens** [comment] 2015-03-29 23:18
I personally don't think de duplication is the responsibility of this library, given it is entirely a user input problem.

**Comment by JedWatson** [comment] 2015-03-30 00:09
Can someone put forward the use-case that is driving this requirement? (I mean big picture, not simple example)

Looking at the complexity of implementation I'm inclined to agree with @dcousens

**Comment by longlho** [comment] 2015-03-30 03:18
So my use case is that a React component which uses this library to allow class name overwrites w/ a specific set of default classNames, so something like `classNames('foo', extraStuff)`. 

Conceptually since this library allows a chaining/combining a set of class names, specifying `{foo: false}` at the end of the chain and have it still appear in the output makes it very hard to debug, as you basically have to crawl down the chain of abstractions and figure out which layer injected `foo` in. And since `foo` will always be there you need to have hacky CSS rule to make certain selectors more specific and/or throw `!important` in there.

**Comment by cezar-berea** [comment] 2015-03-30 14:05
I agree with @dcousens  but I also have 2 compelling reasons for adding this in anyway:

1. In order to do the de-duplication outside of the library one would have to parse the inputs and do most of the work that the library already does.

2. Allowing later arguments to overwrite previous arguments is more idiomatic and almost expected behavior (think `_.extend`).

**Comment by longlho** [comment] 2015-03-30 14:34
@cezar-berea We're having some discussion in the PR itself. @JedWatson mentioned exposing `.dedupe` (or `.merge` if we wanna be similar to `_.merge`) and I think that's probably best as an opt-in due to performance impact

**Comment by longlho** [comment] 2015-03-31 13:47
just fixed it

**Comment by dcousens** [comment] 2015-04-20 02:26
@JedWatson what is your conclusion here, `.dedupe`?

**Comment by 3den** [comment] 2015-04-30 22:39
can someone get that merged?

**Comment by JedWatson** [comment] 2015-05-01 15:33
@3den will land it this weekend.

**Comment by dcousens** [comment] 2015-05-03 02:34
@JedWatson as `.dedupe`?

**Comment by dcousens** [comment] 2015-05-03 10:03
Closing this in favour of https://github.com/JedWatson/classnames/issues/31

**Closed by dcousens** 2015-05-03 10:03 UTC

**Comment by JedWatson** [comment] 2015-05-05 11:00
Just released 2.1.0 with this included.
