### ISSUE TITLE
Advanced typing for classnames/bind

### ISSUE THREAD

**Issue by IMalyugin** [JedWatson/classnames#300] opened 2023-02-06 16:20 UTC
Been looking for a way to type classnames properly for quiet some time, found a way:

Using https://www.npmjs.com/package/css-modules-typescript-loader along with advanced classnames/bind typing would let us typecheck all the bound arguments, leveling classnames/bind up to the new heights.

Would a PR with the following typing be welcome?
```typescript
type StyleSheetClasses = { [name: any]: string };


/**
 * Type definition for arguments of cn (class-1, class-2, class-3)
 *   className={cn('class-1', 'class-2', { 'class-3': flag })}
 */
export type CxArgument<CL extends StyleSheetClasses> = CL | Partial<Record<CL, boolean | string | number | undefined>>;

/**
 * Type definition for cn:
 *   const cn = classnames.bind(styles)
 */
export type CxBind<CL extends StyleSheetClasses> = (...args: CxArgument<CL>[]) => string;

/**
 * Type definition for bind:
 *   import { bind } from 'classnames/bind';
 */
export type ClassNamesBind = <CL extends StyleSheetClasses>(styles: CL) => CxBind<keyof CL>;

export declare module 'classnames/bind' {
  export const bind: ClassNamesBind;
  export default {
    bind,
  };
}
```

Works for both strings and record:
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/18382880/217026204-4d91d1fa-c259-4713-b4a9-ba3602561992.png">

**Comment by nagman** [comment] 2023-03-16 07:49
Wow, man you're a genius!
In your types definition there's no type for arrays, but I never use arrays with classnames.bind (and who does?).
So it's not perfect regarding to the features of the package, but regarding to me it's perfect, it does all what I need :)
If I encounter errors with those types I'll let you know in this thread

**Comment by nagman** [comment] 2023-03-16 08:18
And for those who are stumbling upon this thread, here's the way I solved typed css modules with classnames.bind:

1. Install the VS Code extenstion `awwit.typed-css-modules-plugin`
2. Install the `typed-css-modules` package within your directory (with npm or yarn, as you wish)
3. Put `// @type` at the top of the css (or scss) files you want to be processed
4. Save your css file and you should have a css.d.ts file created with all classnames exported
5. Create a `classnames.d.ts` file at the root of your project (or in the src directory) with the code @IMalyugin provided
6. And you're good to go!

I prefer installing a VS Code extension rather than a webpack plugin or a standalone script because: 1) I'm a bit afraid of changing the webpack configuration ; and 2) I already have so many scripts running in my terminal, I prefer to keep it lean.

**Comment by IMalyugin** [comment] 2023-03-16 17:26
Glad that worked out for you!

Didn't have time to integrate it ourselves, the issue with generating .d.ts too late stuttered me.
If .d.ts files are up to date - everything's great, but once new css-files are added or existing css-files are modified, we have to rely on webpack being launched, plus accept the delay.

Not sure if those are still issues using vscode extension (i'm using `JetBrains line, not even sure there is a similar extension for me). If not, it would probably have to be some IDe-integrated in-memory stylesheet type parser.

Keep us posted If you run in any issues with your setup. :)

**Comment by jonkoops** [comment] 2023-12-14 17:17
Duplicate of #299

**Closed** 2023-12-14 17:17 UTC
Labels: feature, types
