### ISSUE TITLE
Getting error says 'this'  context of type 'void' is not assignable

### ISSUE THREAD

**Issue by rafeekasharaf** [JedWatson/classnames#309] opened 2023-05-12 13:58 UTC
The 'this' context of type 'void' is not assignable to method's 'this' of type 'Binding | undefined'

**Comment by dcousens** [comment] 2023-05-13 09:28
Hi @rafeekasharaf,

Could you please provide an example of how to reproduce this type error?

**Comment by paulinecpz** [comment] 2023-05-17 08:22
Hey there,
Getting the same error
typed as follow :
`const cx = classNames.bind(styles) as typeof classNames;
`

used as follow :

`<div className={cx('white-bg')}>HELLO</>`

I could correct it typing like this, but not sure that is the right way.
`const cx = classNames.bind(styles) as (...classNames: string[]) => string;
`

**Comment by jonkoops** [comment] 2023-12-14 17:14
Seems like this is a type-safety issue stemming from the fact that `Function.prototype.bind()` itself is not type-safe, and instead returns `any`. This seems to be the same issue as #299, so I will close this as a duplicate.

**Comment by jonkoops** [comment] 2023-12-14 17:14
Duplicate of #299

**Closed** 2023-12-14 17:14 UTC
Labels: bug, types
