### ISSUE TITLE
SyntaxError: Unexpected end of script (Mobile Safari)

### ISSUE THREAD

**Issue by moaazbhnas228** [JedWatson/classnames#312] opened 2023-07-03 08:00 UTC
**browser**: Mobile Safari 16.1
**Device**: iPhone
**Error message**: SyntaxError: Unexpected end of script

Our website monitor reported a syntax error a few times when Safari mobile browsers process this block of code:
![image](https://github.com/JedWatson/classnames/assets/111786023/3c1075ce-65fe-4f4b-9411-81579ea374b9)

On Apple community, they describe the error as:

> The message means a script was running and came to an end before it was finished.
>  To fix it, examine and correct the script.

Why does this error occur in Safari Mobile browsers only, and how to prevent it from happening?

**Comment by moaazbhnas228** [comment] 2023-07-06 07:41
@dcousens Can I get help with this please?

**Comment by jonkoops** [comment] 2023-12-14 16:45
I am unable to reproduce this issue on the latest mobile Safari, and considering the code here is perfectly valid JavaScript, this is likely a bug in older Safari versions.

@moaazbhnas228 do you have a re-producible case for this? Something that can be checked locally and fails every time?

**Comment by jonkoops** [comment] 2023-12-14 17:04
Just tried this again with the iOS simulator set to version 16.1 (same as the report), but everything still works as expected. To attempt to re-create this issue I added a `debug.html` to the project and served it locally:

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Debug</title>
  </head>
  <body>
    <script src="./index.js"></script>
    <script>
      console.log(classNames('foo', 'bar'));
    </script>
  </body>
</html>
``` 

It seems that this issue is not in the library, but rather somewhere else in the tool-chain (e.g. error reporting software, bundler, etc). I am closing this issue, if there is a way to reproduce this let me know and I will re-open.

**Closed by jonkoops** 2023-12-14 17:04 UTC
Labels: bug

**Comment by moaazbhnas228** [comment] 2023-12-14 17:20
Thank you guys
Actually the disappeared from the logs long ago
